### ISSUE TITLE
how to handle this use case

### ISSUE THREAD

**Issue by user1396** [MichielDeMey/express-jwt-permissions#12]
Is there a way to configure such that permission should be granted if either "user:read" or "user:write" strings are present in the permissions object array of strings in the token payload?

**Comment by MichielDeMey** [comment]
This cannot be configured through this middleware, since the permission checks are very strict for security reasons.

What you can do is modify your JWT token's permission object to include something like "user:read_or_write" and you'll have to set this permission in your backend based on your custom logic.

e.g.
```javascript
"permissions": [
  "status",
  "user:read",
  "user:write",
  "user:read_or_write"
]
```

Or, if you'd like to be more generic, you can simply have a "user" permission and you can allow any action.

e.g.
```javascript
"permissions": [
  "status",
  "user",
]
```

I hope that helps.

**Comment by user1396** [comment]
Thank you very much Michiel.

**Comment by jduhls** [comment]
>  permission checks are very strict for security reasons.

Could someone elaborate on the "security reasons" for not implementing a "one of" check on the permissions array (instead of "all of" as it is now)?
